### ISSUE TITLE
일기 모델 만들기

### ISSUE THREAD

**Issue by jupiny** [jupiny/EnglishDiary#11]
- user
- conent
- hash_id
- diary_image
- word_count(사용한 단어 수)
- diary_type(추후에 필요할 수 있으므로)
- created_at
- updated_at

**Comment by samkugji** [comment]
hash_id는 어떻게 활용되는지 궁금합니다. 일기 링크를 축약하는데 쓰이나요?

**Comment by jupiny** [comment]
아 일기 관련된 url에 diary_id가 적나라하게 나오지 않고 hash_id가 나오는 것이 더 보안상 좋을 거 같아 사용하였습니다.

ex).../diary/1/edit => .../diary/Aei$IFLp/edit

**Comment by jupiny** [comment]
승환아 잘했어!
