### ISSUE TITLE
ajax를 통한 일기 CRUD 기능 구현하기

### ISSUE THREAD

**Issue by jupiny** [jupiny/EnglishDiary#17]
ajax를 통해 4가지 구현하기
1. 달력에서 날짜를 클릭했을 때 해당하는 날짜의 일기 내용을 보여준다. 일기가 없을 시에는 빈 내용 출력
2. 일기를 작성한 후 저장 버튼을 누르면, 일기 생성
3. 기존의 내용이 적혀있는 일기의 경우, 수정한 후 저장 버튼을 누르면 해당하는 일기 업데이트
4. 삭제 버튼을 누르면, 해당하는 일기 삭제

**Comment by samkugji** [comment]
월요일에 수찬쌤에게 질뭉할게 있어
단어수 세는 기능을 소셜로그인보다 
먼저 구현하려고 하는데
일기 저장 (포스트 기능) 우선순위를 높여주셨으면 합니다

**Comment by jupiny** [comment]
단어 수 세는 기능은 이미 넣었고 ajax를 통해 일기 저장되는 것만 구현하면 됩니다. 오늘 안에 끝내보겟습니당.

**Comment by samkugji** [comment]
헉 이러시면 곤란합니다 ㅋㅋ

**Comment by samkugji** [comment]
그거 제가 하려고 했는데 벌써 가져가서 해치우시다니 ㅋㅋㅋ

**Comment by jupiny** [comment]
아 그거 그냥 split 함수 썼을 뿐입니다 ㅋㅋㅋ 코드도 보면 정말 간단합니다.

**Comment by jupiny** [comment]
수고하셨습니다 승환씨
