### ISSUE TITLE
analysis function by basic math & word2vec

### ISSUE THREAD

**Issue by samkugji** [jupiny/EnglishDiary#27]
- basic static (show in Mypage template)
- autocomplete function
- Word Cloud (show words that a user is used to)
- diary emotion
- synonyms for English Level Up!
   crawling : http://www.wordreference.com/synonyms/call
                    http://www.thesaurus.com/browse/detect

**Comment by samkugji** [comment]
Exit 를 목표로 하여 다음과 같이 작업 우선순위를 변경한다.
1. 배포
2. 소셜 회원가입, 소셜 로그인
3. 통계 매니저 기본 기능(한 달 중 달성률, 사용한 단어 수, 총 일기 수)
4. CSS 다듬기
5. 통계 매니저 고급 기능
6. 셀러리를 사용한 알림기능

**Comment by jupiny** [comment]
화이팅입니다!

**Comment by samkugji** [comment]
주피니가 배포까지 하셨습니다.
